[package]
name = "fall_gen"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
tera = "1.5.0"
clap = "2.20"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
failure = "0.1"


fall_tree = { path = "../tree" }
fall_parse = { path = "../parse" }
lang_fall = { path = "../../lang/fall" }

[dev-dependencies]
tempdir = "0.3"
