[package]
name = "lang_fall_syntax"
version = "0.1.0"
edition = "2018"

[dependencies]
regex = "1"
proptest = "0.3"
fall_tree = { path = "../../../fall/tree" }
fall_parse = { path = "../../../fall/parse" }
