[package]
name = "lang_rust"
version = "0.1.0"

[dependencies]
file = "*"
elapsed = "*"
fall_tree = { path = "../../fall/tree" }
fall_parse = { path = "../../fall/parse" }
fall_editor = { path = "../../fall/editor" }
