[package]
name = "lang_fall"
version = "0.1.0"

[dependencies]
itertools = "0.7"
rental = "0.4"
serde = "1.*"
serde_derive = "1.*"
regex = "0.2"

fall_tree = { path = "../../fall_tree" }
fall_parse = { path = "../../fall_parse" }

