[package]
name = "lang_fall"
version = "0.1.0"

[dependencies]
itertools = "0.7.4"
rental = "0.4"
serde = "1.*"
regex = "0.2"

fall_tree = { path = "../../fall/tree" }
fall_parse = { path = "../../fall/parse" }
fall_editor = { path = "../../fall/editor" }
lang_fall_syntax = { path = "./syntax" }
