[package]
name = "lang_rust_syntax"
version = "0.1.0"

[dependencies]
regex = "0.2"
fall_tree = { path = "../../../fall/tree" }
fall_parse = { path = "../../../fall/parse" }

[dev-dependencies]
file = "*"
elapsed = "*"
proptest = "0.3"