[package]
name = "fall_test"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
fall_tree = { path = "../fall_tree" }
fall_parse = { path = "../fall_parse" }
lang_json = { path = "../lang/json" }
