[package]
name = "fall_parse"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
lazy_static = "1"
fall_tree = { path = "../tree" }
m_lexer = "0.0.1"
