[package]
name = "fall_parse"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
lazy_static = "1"
fall_tree = { path = "../tree" }
m_lexer = "0.0.4"
typed_index_derive = "0.1.2"
