[package]
name = "fall_tree"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"

[dependencies]
fall_text = { path = "../text" }
serde = "1.*"
serde_derive = "1.*"
difference = "1.0.0"
elapsed = "0.1"
file = "*"
